CREATE TABLE `CUSTOMER` (
  `CUSTOMER_NAME` varchar(20) DEFAULT NULL,
  `CUSTOMER_ID` int(11) NOT NULL,
  `CPHONE` varchar(20) DEFAULT NULL,
  `GENDER` varchar(20) DEFAULT NULL,
  `CADDRESS` varchar(20) DEFAULT NULL,
  PRIMARY KEY (`CUSTOMER_ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_general_ci;

INSERT INTO `CUSTOMER` (`CUSTOMER_NAME`, `CUSTOMER_ID`, `CPHONE`, `GENDER`, `CADDRESS`) VALUES
('NANDANA', 52, '6790456', 'FEMALE', 'KOZHIKODE'),
('NEHAL', 53, '1456456', 'FEMALE', 'NEWYORK'),
('NIKHIL', 54, '123456', 'MALE', 'LONDON'),
('NIVED', 55, '18980456', 'MALE', 'JAPAN'),
('NORA', 56, '8980456', 'FEMALE', 'PAla'),
('RAHUL', 58, '8747424', 'MALE', 'TVM');
